### PR TITLE
Setup kafka and s3 integration; implement api split

### PR DESCRIPTION
**Pull request by BlakeHolifield**
* Adds S3 bucket support
* Adds kafka messaging
* Split `/v1/generate` into `/v2/create`, `/v2/status/:statusID`, and `v2/download/:ID`
* Uses a temporary local store mechanism to keep filepaths in memory

When a request is sent to `/v2/create`, a worker node is sent the work and the API will return 202 with an ID. Once that worker node has finished the work, a kafka message is sent back and the ID struct is updated to with the finished filepath. The path is then uploaded into S3 for storage and the UI will return that data. The UI can then check the status of a pdf from the `v2/status/:statusID` endpoint and download it from `v2/download/:ID`

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@BlakeHolifield 

The SNYK
```
Avoid hardcoding values that are meant to be secret. Found a hardcoded string used in here.

‎src/common/config.ts

line 47  secretKey: process.env.MINIO_SECRET_KEY || 'minioadmin',
line 52  secretKey: process.env.MINIO_SECRET_KEY || 'minioadmin',

...

Unsanitized input from an HTTP parameter flows into <unknown>, where it is used as a path. This may result in a Path Traversal vulnerability and allow an attacker to read arbitrary files.

‎src/server/routes/routes.ts
                                         _______________
line 189 return res.status(200).sendFile(status.filepath, (err) => {
```

**Comment by Hyperkid123** [comment]
@BlakeHolifield looks like the rebase got messed up.

**Comment by BlakeHolifield** [comment]
Going to use main

**Pull request closed without merging**
