### PR TITLE
RHIROS-861 ROS Executive Report V2

### PR DESCRIPTION
**Pull request by PreetiW**
### Description

Migration of ROS Executive report to V2
**Jira:** https://issues.redhat.com/browse/RHIROS-861

**PDFs:** https://drive.google.com/file/d/1xuL0j6yG508oF41VurfqMIuhIiDARfb0/view?usp=share_link

### CODE REVIEW

**Review by Hyperkid123 — APPROVED** [review]
LGTM

**Comment by Hyperkid123** [comment]
@PreetiW let me know when this is ready for merge.

**Comment by PreetiW** [comment]
sure @Hyperkid123 I have shared the mockups with UX team, just waiting for their ACK and then I will update you!

**Comment by PreetiW** [comment]
@Hyperkid123 I got ACK from UX team and I just made minor adjustments in the graph alignment and size. You can check the changes in the last few commits and after that please go ahead and merge the PR if everything looks good 💯 Thanks for taking time to review 🙌🏻

**Pull request merged**
